In [9]:
import pandas as pd


data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, None, 30],
        'Score': [90, 85, None]}

df = pd.DataFrame(data)

print('결측치 여부 확인:')
print(df.isnull())

결측치 여부 확인:
    Name    Age  Score
0  False  False  False
1  False   True  False
2  False  False   True

In [2]:
print('컬럼별 결측치 개수:')
print(df.isnull().sum())

컬럼별 결측치 개수:
Name     0
Age      1
Score    1
dtype: int64

In [10]:
df.dropna(axis=0, how='any', subset=None, inplace=False)

    Name   Age  Score
0  Alice  25.0   90.0

In [16]:
df.fillna(45, inplace=False)

      Name   Age  Score
0    Alice  25.0   90.0
1      Bob  45.0   85.0
2  Charlie  30.0   45.0

In [17]:
mean_age = df['Age'].mean()
df['Age'] = df['Age'].fillna(mean_age)
print('Age 열 평균값으로 결측치 대체:')
print(df)

Age 열 평균값으로 결측치 대체:
      Name   Age  Score
0    Alice  25.0   90.0
1      Bob  27.5   85.0
2  Charlie  30.0    NaN

In [18]:
df['Score'] = df['Score'].fillna(0)
print('Score 열 0으로 결측치 대체:')
print(df)

Score 열 0으로 결측치 대체:
      Name   Age  Score
0    Alice  25.0   90.0
1      Bob  27.5   85.0
2  Charlie  30.0    0.0

In [19]:
print('결측치 확인:')
print(df.isnull().sum())

mean_age = df['Age'].mean()
df['Age'] = df['Age'].fillna(mean_age)

결측치 확인:
Name     0
Age      0
Score    0
dtype: int64

In [21]:
data = {'Height': [150, 160, 170, 180, 350]}
df = pd.DataFrame(data)

print('데이터\n', df)

print('\nHeight의 최대값:', df['Height'].max())
print('Height의 최소값:', df['Height'].min())

데이터
    Height
0     150
1     160
2     170
3     180
4     350

Height의 최대값: 350
Height의 최소값: 150

In [25]:
Q1 = df['Height'].quantile(0.25)
Q3 = df['Height'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df['Height'] < lower_bound) | (df['Height'] > upper_bound)]
print('IQR 기준으로 찾은 이상치:\n', outliers)

IQR 기준으로 찾은 이상치:
    Height
4     350

In [26]:
from scipy.stats import zscore

df['Z_Score'] = zscore(df['Height'])
print('\nZ-스코어:\n', df)

outliers = df[df['Z_Score'].abs() > 3]
print('\nZ-스코어 기준으로 찾은 이상치:\n', outliers)

Z-스코어:
    Height   Z_Score
0     150 -0.696373
1     160 -0.562455
2     170 -0.428537
3     180 -0.294619
4     350  1.981985

Z-스코어 기준으로 찾은 이상치:
 Empty DataFrame
Columns: [Height, Z_Score]
Index: []

In [29]:
df_cleaned = df[(df['Height'] >= lower_bound) & (df['Height'] <= upper_bound)]
print('\n이상치 제거 후 데이터:\n', df_cleaned)

이상치 제거 후 데이터:
    Height   Z_Score
0     150 -0.696373
1     160 -0.562455
2     170 -0.428537
3     180 -0.294619

In [31]:
median_value =  df[(df['Height'] >= lower_bound) & (df['Height'] <= upper_bound)]['Height'].median()
df['Height'] = df['Height'].apply(lambda x: median_value if (x < lower_bound or x > upper_bound) else x) 
print('이상치를 중앙값으로 대체한 데이터:\n', df)

이상치를 중앙값으로 대체한 데이터:
    Height   Z_Score
0   150.0 -0.696373
1   160.0 -0.562455
2   170.0 -0.428537
3   180.0 -0.294619
4   165.0  1.981985

In [32]:
pd.cut(x, bins, labels=None, right=True)

NameError: name 'x' is not defined

In [38]:
data = {'Age': [15,22,35,50,72]}
df = pd.DataFrame(data)

bins = [0, 20, 30, 40, 100]
labels = ['10대', '20대', '30대', '40대 이상']
df['Age_Group'] = pd.cut(df['Age'], bins=bins, labels=labels)


print(df)

   Age Age_Group
0   15       10대
1   22       20대
2   35       30대
3   50    40대 이상
4   72    40대 이상

In [40]:
df['Age_Quantile'] = pd.qcut(df['Age'], q=3, labels=['하위', '중위', '상위'])

print(df)

   Age Age_Group Age_Quantile
0   15       10대           하위
1   22       20대           하위
2   35       30대           중위
3   50    40대 이상           상위
4   72    40대 이상           상위

In [41]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

data = {'Height': [150, 160, 170, 180, 190]}
df = pd.DataFrame(data)

scaler = MinMaxScaler()
df['Height_Normalized'] = scaler.fit_transform(df[['Height']])

print(df)

   Height  Height_Normalized
0     150               0.00
1     160               0.25
2     170               0.50
3     180               0.75
4     190               1.00

In [43]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

data = {'Weight': [50,60,70,80,90]}
df = pd.DataFrame(data)

scaler = StandardScaler()
df['Weight_Standardized'] = scaler.fit_transform(df[['Weight']])
                                                     
print(df)

   Weight  Weight_Standardized
0      50            -1.414214
1      60            -0.707107
2      70             0.000000
3      80             0.707107
4      90             1.414214

In [44]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

data = {'City': ['서울', '부산', '대구', '서울', '부산']}
df = pd.DataFrame(data)

encoder = LabelEncoder()
df['City_Encoded'] = encoder.fit_transform(df['City'])

print(df)

  City  City_Encoded
0   서울             2
1   부산             1
2   대구             0
3   서울             2
4   부산             1

In [45]:
import pandas as pd


data = {'City': ['서울', '부산', '대구', '서울', '부산']}
df = pd.DataFrame(data)

df_encoded = pd.get_dummies(df, columns=['City'])

print(df_encoded)

   City_대구  City_부산  City_서울
0    False    False     True
1    False     True    False
2     True    False    False
3    False    False     True
4    False     True    False

In [47]:
import pandas as pd


data = {'Name': ['Alice', 'Bob', 'Charlie','David'],
        'Age': [25, 30, 35, 40],
        'Score': [90, 85, 75, 60]}

df = pd.DataFrame(data)

df_dropped = df.drop(index=2)

print('특정 행 삭제 후 데이터:')
print(df_dropped)

특정 행 삭제 후 데이터:
    Name  Age  Score
0  Alice   25     90
1    Bob   30     85
3  David   40     60

In [48]:
df_dropped = df.drop(columns=['Score'])

print('특정 열 삭제 후 데이터:')
print(df_dropped)

특정 열 삭제 후 데이터:
      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

In [50]:
data_with_na = {'Name': ['Alice', 'Bob', 'Charlie','David'],
        'Age': [25, None, 35, 40],
        'Score': [90, 85, None, 60]}

df_with_na = pd.DataFrame(data_with_na)

df_cleaned = df_with_na.dropna()
print('결측치가 포함된 행 삭제 후 데이터:')
print(df_cleaned)

결측치가 포함된 행 삭제 후 데이터:
    Name   Age  Score
0  Alice  25.0   90.0
3  David  40.0   60.0

In [ ]:
data_with_duplicates = {'Name': ['Alice', 'Bob', 'Charlie','David'],
        'Age': [25, 30, 35, 40],
        'Score': [90, 85, 90, 60]}
df_with_duplicates = pd.DataFrame(data_with_duplicates)